{
    .slug    = "why-c-wasm",
    .title   = "Why I Built This Blog in C and WebAssembly",
    .date    = "2026-02-18",
    .excerpt = "Most people reach for React or Hugo. I reached for malloc.",
    .content =
        "## The Obvious Question\n\n"
        "Why would anyone write a blog engine in C and compile it to WebAssembly? "
        "The honest answer: because it's interesting. There's something satisfying about "
        "writing `printf` and having it appear in a browser tab instead of a terminal.\n\n"
        "## How It Works\n\n"
        "This entire page — the post list, the routing, the markdown rendering — is running "
        "inside a `.wasm` binary that your browser downloaded. The C code uses Emscripten's "
        "`EM_JS` macro to call JavaScript functions that manipulate the DOM. The C code owns "
        "the logic. JavaScript is just a thin bridge to the browser's rendering engine.\n\n"
        "The flow looks like this:\n\n"
        "```\n"
        "blog.c  →  emcc  →  blog.wasm + blog.js\n"
        "                          ↓\n"
        "               browser loads & runs\n"
        "                          ↓\n"
        "               C reads window.location.hash\n"
        "                          ↓\n"
        "               C generates HTML string\n"
        "                          ↓\n"
        "               EM_JS sets innerHTML\n"
        "```\n\n"
        "## The Stack\n\n"
        "- **Language**: C (C11)\n"
        "- **Compiler**: `emcc` (Emscripten 5.0.1)\n"
        "- **Runtime**: WebAssembly in the browser\n"
        "- **DOM bridge**: `EM_JS` macros\n"
        "- **Routing**: hash-based (`blog.html#post-slug`)\n"
        "- **Hosting**: GitHub Pages\n\n"
        "## What's Actually Cool About This\n\n"
        "WebAssembly runs at near-native speed. For a blog this doesn't matter — "
        "HTML string manipulation doesn't need to be fast. But the games on this site "
        "do. The snake game, the Tetris clone, the 3D raycasting maze — those are all "
        "C code running in the browser via the same pipeline.\n\n"
        "The entire site is C. No JavaScript frameworks. No npm. No `node_modules` folder "
        "with 50,000 files. Just `emcc` and some HTML shells.\n\n"
        "## Try It\n\n"
        "Everything lives at `aetiss.github.io`. The source is straightforward — "
        "if you can read C, you can read everything that renders this page."
},
